version: '3.8'

services:
  take-home-task:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    environment:
      - DATABASE_URL=mysql+mysqlconnector://mysql:mysql@localhost/forsit

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: forsit
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  alembic:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
    environment:
      - DATABASE_URL=mysql+mysqlconnector://root:mysql@mysql:3306/forsit
    command: pipenv run alembic upgrade head
